Integrate with multiple regions
rundeck-plugins/rundeck-ec2-nodes-plugin pull request #117
Opened 2022-03-11 17:16 UTC by jsboak

This PR enables a single node-source to integrate (pull in EC2's) from multiple regions by specifying multiple **Endpoints** using a comma-separated list of EC2 "endpoints":
![Screen Shot 2022-03-10 at 5 50 03 PM](https://user-images.githubusercontent.com/11511251/157914980-bb5b5ef3-4d6f-4ea3-a6b2-8521d2342879.png)

![Screen Shot 2022-03-10 at 5 49 16 PM](https://user-images.githubusercontent.com/11511251/157914562-8b161c4d-f319-4f3c-9f52-bd408ab5f294.png)

The changes have been tested to work with: single endpoints, multiple endpoints, space(s) between commas, and misspelled endpoints:
![Screen Shot 2022-03-11 at 9 04 34 AM](https://user-images.githubusercontent.com/11511251/157914718-8d3e586a-2618-4cae-be19-c7a8b83858be.png)

2022-03-11 17:24 UTC, fdevans commented
This may require #118 to complete successfully.

2022-03-30 21:43 UTC, qualman commented on src/main/java/com/dtolabs/rundeck/plugin/resources/ec2/InstanceToNodeMapper.java
> +        if (getEndpoint().equals("ALL_REGIONS")) {
This needs to be `if (getEndpoint() == "ALL_REGIONS") {`

2022-03-30 22:39 UTC, qualman requested changes
Just a few things to adjust! If you make the changes I laid out (or something similar), you end up with 3 tests that just need to be adjusted:

```
Failed to parse endpoint: Region cannot be empty
java.lang.IllegalArgumentException: Failed to parse endpoint: Region cannot be empty
	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapper.performQuery(InstanceToNodeMapper.java:120)
	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapperSpec.extra mapping image(InstanceToNodeMapperSpec.groovy:213)


Failed to parse endpoint: Region cannot be empty
java.lang.IllegalArgumentException: Failed to parse endpoint: Region cannot be empty
	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapper.performQuery(InstanceToNodeMapper.java:120)
	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapperSpec.extra mapping not calling image list(InstanceToNodeMapperSpec.groovy:254)


Failed to parse endpoint: Region cannot be empty
java.lang.IllegalArgumentException: Failed to parse endpoint: Region cannot be empty
	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapper.performQuery(InstanceToNodeMapper.java:120)
	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapperSpec.adding region to the node attributes(InstanceToNodeMapperSpec.groovy:293)


com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapperSpec > extra mapping image FAILED
    java.lang.IllegalArgumentException at InstanceToNodeMapperSpec.groovy:213
    java.lang.IllegalArgumentException at InstanceToNodeMapperSpec.groovy:213
com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapperSpec > extra mapping not calling image list FAILED
    java.lang.IllegalArgumentException at InstanceToNodeMapperSpec.groovy:254
com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapperSpec > adding region to the node attributes FAILED
    java.lang.IllegalArgumentException at InstanceToNodeMapperSpec.groovy:293
17 tests completed, 3 failed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
```

 After that, this should be good to go.

2022-04-01 20:17 UTC, jsboak commented
@qualman want to take a look again and make sure all looks good?

2022-04-05 17:32 UTC, qualman commented
Okay, mea culpa, I think I misread an error or something. I think it _does_ in fact need to be `getEndpoint().equals("ALL_REGIONS")`, and that's the error here. I am going to test that real quick

2022-04-05 18:29 UTC, qualman commented
Okay, @jsboak, I pushed a change that fixes that, and I tested locally and all is well. I am going to wait for tests and then we're ready to go

2022-04-05 18:31 UTC, merged